version: '3.8'

services:
  # 1. Baza de date MySQL
  db:
    image: mysql:8.0
    container_name: hospital_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Aplicația Unificată (Nuxt 3 Frontend + Backend)
  app:
    build: ./client
    container_name: hospital_app
    restart: always
    ports:
      - "3000:3000"
    # Citeste variabilele standard din .env
    env_file:
      - ./client/.env
    environment:
      # Suprascriem doar pentru contextul Docker (unde baza de date nu este localhost, ci se cheamă "db")
      DB_HOST: db
      DB_PORT: 3306
      HOST: 0.0.0.0
    depends_on:
      - db
    volumes:
      - ./client:/app
      - /app/node_modules
      # Pastram folderul cu imaginile pacientilor in afara containerului ca sa nu se piarda
      - ./client/public/uploads:/app/public/uploads

volumes:
  mysql_data: